baseURL = 'https://openmodelica.org/'
languageCode = 'en-us'
title = 'OpenModelica'
theme = 'openmodelica'

[params]
  current_version = {release = '1.26.2', stable = '1.26.2', nightly = '1.27.0-dev'}
  current_branch = {release = 'v1.26.2', stable = 'maintenance/v1.26', nightly = 'master'}
  bugreporting = 'https://github.com/OpenModelica/OpenModelica/blob/master/BUGREPORTING.md'
  roadmap = 'https://github.com/OpenModelica/OpenModelica/milestones'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      # Raw HTML is part of the Joomla export
      unsafe = true

[blackfriday]
extensions = [
    "DefinitionLists",
]

[markup.highlight]
  noClasses=false
